(async()=>{
 const root=document.querySelector('#imagination');if(!root)return;
 const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 const tasks=[['simple_spread','MPE · Spread'],['simple_tag','MPE · Tag'],['simple_world','MPE · World'],['3m','SMAC · 3m'],['2s3z','SMAC · 2s3z'],['5m_vs_6m','SMAC · 5m vs 6m'],['8m','SMAC · 8m'],['2ant','MuJoCo · 2Ant'],['4ant','MuJoCo · 4Ant']];
 const palette=['#8054d3','#e58b39','#169e99','#db587e','#447ed3','#778d36','#b27531','#686fc4'];
 let lang='zh',mode='rollout',task='',data=null,idx=0,time=0,last=0,playing=true,visible=false,version=0,selected=null,predView='state',cache={},cards=[],available=[],taskInfo={};
 const tr=(a,b)=>lang==='zh'?a:b,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),duration=()=>mode==='rollout'?.65:8.8,phase=()=>time<1.4?0:time<4.9?1:time<6.7?2:3;
 const taskText={simple_spread:['三个智能体分别靠近目标，协作完成覆盖。','Three agents coordinate to cover three targets.'],simple_tag:['协作追捕：彩色圆是追捕者，红色圆是逃跑者，灰色圆是障碍物。','Cooperative pursuit: colored dots are pursuers, red dots are the evader, and gray circles are obstacles.'],simple_world:['协作追捕任务，包含障碍物和场景地标。红色圆为未由该策略控制的对手。','Cooperative pursuit with obstacles and landmarks. Red dots are opponents outside the controlled team.'],smac:['紫色是己方，红色是敌方；血条和位置来自实际仿真状态。','Purple units are allies; red units are enemies. Positions and health come from recorded simulator states.'],ant:['多个智能体共同控制一只 Ant 的不同关节。左图是实际身体运动的侧视示意，不是多个独立机器人。','Multiple agents control different joints of one Ant. The left panel is a side-view schematic of its actual body motion, not separate robots.']};
 function context(canvas){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.fillStyle='#f9f8fd';c.fillRect(0,0,canvas.width,canvas.height);c.font='14px system-ui';return c}
 function circle(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()}
 function frame(d,f){return f<.5?d.state:d.next_state}
 function mix(a,b,f){return a+(b-a)*f}
 function world(canvas,d,f){const c=context(canvas),w=canvas.width,h=canvas.height;
  if(data.domain==='MPE'){
   const extent=data.displayExtent,sc=(Math.min(w,h)-60)/(extent*2),xy=p=>[w/2+p.x*sc,h/2-p.y*sc];
   d.state.landmarks.filter(l=>!l.boundary).forEach(p=>{let [x,y]=xy(p);if(task==='simple_spread'){c.strokeStyle='#a99cbd';c.lineWidth=3;c.beginPath();c.arc(x,y,13,0,Math.PI*2);c.stroke()}else circle(c,x,y,Math.max(4,p.radius*sc),'#bdc2cc')});
   if(mode==='imagination'&&phase()>=2){let ci=selected??d.selected;for(let a=0;a<data.n_agents;a++){c.strokeStyle=palette[a%8];c.lineWidth=2;c.setLineDash([6,5]);c.beginPath();d.predicted_obs[ci].forEach((o,j)=>{let p=xy({x:o[a][2],y:o[a][3]});j?c.lineTo(...p):c.moveTo(...p)});c.stroke();c.setLineDash([])}}
   d.state.agents.forEach((p,a)=>{const q=d.next_state.agents[a],pt=xy({x:mix(p.x,q.x,f),y:mix(p.y,q.y,f)});circle(c,...pt,a<data.n_agents?10:11,a<data.n_agents?palette[a%8]:'#dd5263');c.fillStyle='#fff';c.textAlign='center';c.fillText(a<data.n_agents?String(a+1):'E',pt[0],pt[1]+5)});
  }else if(data.domain==='SMAC'){
   const {xs,ys,cx,cy}=data.displayBounds,sc=(Math.min(w,h)-100)/Math.max(12,Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys));
   for(const key of ['agents','enemies'])d.state[key].forEach((p,i)=>{const q=d.next_state[key][i],x=w/2+(mix(p.x,q.x,f)-cx)*sc,y=h/2-(mix(p.y,q.y,f)-cy)*sc,hp=mix(p.health,q.health,f);if(hp<=0)return;circle(c,x,y,12,key==='agents'?'#8054d3':'#d85c6a');c.fillStyle='#fff';c.textAlign='center';c.fillText(String(i+1),x,y+5);c.fillStyle='#e0dce6';c.fillRect(x-16,y-23,32,4);c.fillStyle=key==='agents'?'#8054d3':'#d85c6a';c.fillRect(x-16,y-23,32*clamp(hp/p.max_health,0,1),4)});
  }else{
   const a=d.state,b=d.next_state,body=a.bodies.map((p,i)=>p.map((v,k)=>mix(v,b.bodies[i][k],f))),center=mix(a.qpos[0],b.qpos[0],f),sc=150,xy=p=>[w/2+(p[0]-center)*sc,h-55-p[2]*sc];c.strokeStyle='#d7d0e4';c.lineWidth=2;c.beginPath();c.moveTo(20,h-55);c.lineTo(w-20,h-55);c.stroke();
   body.forEach((p,i)=>{const parent=a.parents[i];if(i<2||parent<1)return;c.strokeStyle=palette[Math.floor((i-2)/3)%8];c.lineWidth=7;c.lineCap='round';c.beginPath();c.moveTo(...xy(body[parent]));c.lineTo(...xy(p));c.stroke();circle(c,...xy(p),5,'#5b417e')});circle(c,...xy(body[1]),18,'#8054d3');c.fillStyle='#6c6081';c.textAlign='left';c.fillText(tr('实际身体位置 · 侧视，镜头跟随','Recorded body positions · side view, tracking camera'),20,28);c.fillText('x = '+center.toFixed(2)+' m',20,50);
  }
 }
 function prediction(canvas,d,ci,t){const c=context(canvas),w=canvas.width,h=canvas.height,path=d.predicted_obs[ci],end=Math.min(Math.floor(t),path.length-1);
  if(predView==='state'&&data.domain==='MPE'){
   const vals=d.predicted_obs.flat(2),extent=Math.max(1.3,...vals.map(p=>Math.max(Math.abs(p[2]),Math.abs(p[3]))))*1.1,sc=(Math.min(w,h)-25)/(extent*2),xy=p=>[w/2+p[2]*sc,h/2-p[3]*sc];
   d.state.landmarks.filter(l=>!l.boundary).forEach(p=>{c.strokeStyle='#b8aec8';c.lineWidth=1;c.beginPath();c.arc(w/2+p.x*sc,h/2-p.y*sc,task==='simple_spread'?5:Math.max(2,p.radius*sc),0,Math.PI*2);c.stroke()});
   for(let a=0;a<data.n_agents;a++){c.strokeStyle=palette[a%8];c.setLineDash([4,3]);c.lineWidth=2;c.beginPath();for(let j=0;j<=end;j++){let p=xy(path[j][a]);j?c.lineTo(...p):c.moveTo(...p)}c.stroke();c.setLineDash([]);circle(c,...xy(path[end][a]),4,palette[a%8])}
  }else if(predView==='state'&&data.domain==='SMAC'&&data.layout.obs_own_health){
   const l=data.layout,field=l.id_prefix+l.move+l.enemy[0]*l.enemy[1]+l.ally[0]*l.ally[1],row=(h-30)/data.n_agents;
   c.fillStyle='#78698b';c.font='11px system-ui';c.textAlign='left';c.fillText(tr('预测己方血量比例','Predicted ally health'),8,12);
   for(let a=0;a<data.n_agents;a++){const value=path[end][a][field],y=24+a*row;c.fillStyle='#78698b';c.fillText(String(a+1),8,y+10);c.fillStyle='#e5dfed';c.fillRect(23,y,w-62,Math.min(12,row-4));c.fillStyle=palette[a%8];c.fillRect(23,y,(w-62)*clamp(value,0,1),Math.min(12,row-4));c.fillStyle='#78698b';c.textAlign='right';c.fillText(value.toFixed(2),w-3,y+10);c.textAlign='left'}
  }else if(predView==='state'&&data.forward_position_index!==undefined){
   const k=data.forward_position_index,seqs=d.predicted_obs.map(p=>p.map(o=>o.reduce((sum,a)=>sum+a[k],0)/data.n_agents)),vals=seqs.flat(),lo=Math.min(...vals),hi=Math.max(...vals),xy=(i,v)=>[22+i/data.horizon*(w-42),h-24-(v-lo)/Math.max(.001,hi-lo)*(h-52)];
   c.fillStyle='#78698b';c.font='11px system-ui';c.textAlign='left';c.fillText(tr('预测前进位置 x（米）','Predicted forward x (m)'),8,13);c.strokeStyle='#8054d3';c.lineWidth=2;c.setLineDash([5,3]);c.beginPath();for(let j=0;j<=end;j++){const p=xy(j,seqs[ci][j]);j?c.lineTo(...p):c.moveTo(...p)}c.stroke();c.setLineDash([]);circle(c,...xy(end,seqs[ci][end]),4,'#8054d3');c.fillText(seqs[ci][end].toFixed(3)+' m',8,h-5);
  }else{
   // Cumulative predicted reward is directly defined for every domain; no invented physical coordinates.
   const series=d.predicted_rewards.map(rs=>{let sum=0;return [0,...rs.map(r=>sum+=r)]}),vals=series.flat(),lo=Math.min(0,...vals),hi=Math.max(.1,...vals),xy=(i,v)=>[18+i/data.horizon*(w-36),h-22-(v-lo)/(hi-lo||1)*(h-42)];
   c.strokeStyle='#ddd5e9';c.lineWidth=1;c.beginPath();c.moveTo(...xy(0,0));c.lineTo(...xy(data.horizon,0));c.stroke();c.strokeStyle='#8054d3';c.lineWidth=3;c.setLineDash([5,3]);c.beginPath();for(let j=0;j<=end;j++){const p=xy(j,series[ci][j]);j?c.lineTo(...p):c.moveTo(...p)}c.stroke();c.setLineDash([]);circle(c,...xy(end,series[ci][end]),4,'#8054d3');c.fillStyle='#78698b';c.font='11px system-ui';c.textAlign='left';c.fillText(tr('累计预测回报','Predicted cumulative return'),12,14);c.fillText('0',15,h-5);c.textAlign='right';c.fillText(tr('未来 ','Step ')+data.horizon,w-12,h-5);
  }
 }
 function render(){if(!data)return;const d=data.decisions[idx],ph=phase(),imag=mode==='imagination',reveal=ph>=2,frac=imag?(ph===3?clamp((time-6.7)/1.3,0,1):0):clamp(time/.65,0,1),w=tr;
 all('[data-task]').forEach(b=>{const o=taskInfo[b.dataset.task]?.outcome;const label=tasks.find(t=>t[0]===b.dataset.task)[1];b.textContent=label+' · '+(o?.success===true?w('获胜','Win'):o?.success===false?w('未获胜','No win'):o?.complete?w('整局','Full'):w('片段','Partial'))});$('[data-availability]').textContent=w('可切换 '+available.length+' 个任务：点击上方任务按钮。',available.length+' tasks available. Choose a task using the buttons above.');$('[data-title]').textContent=w('选择任务，看它如何先想再行动。','Choose a task. Watch it imagine, then act.');$('[data-lang]').textContent=lang==='zh'?'English':'中文';
 all('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));b.textContent=b.dataset.mode==='rollout'?w('Rollout · 实际执行','Rollout · execution'):w('Imagination · 模型预测','Imagination · prediction')});
 $('[data-meta]').textContent=data.quality+' · seed '+data.seed+' · '+data.n_agents+' '+w('智能体','agents');const desc=taskText[task]||taskText[data.domain==='SMAC'?'smac':'ant'];$('[data-description]').textContent=desc[lang==='zh'?0:1];
 const outcome=data.outcome;let ending;
 if(outcome?.complete&&typeof outcome.success==='boolean')ending=outcome.success?w('成功：本局获胜','Success: this episode was won'):w('未获胜：本局已结束','No win: this episode has ended');
 else if(outcome?.complete)ending=w('完整回合已结束；该任务未提供二元成功标记','Full episode ended; this task provides no binary success flag');
 else ending=w('片段尚未记录到结局，不能判断成功或失败','The recording does not reach the ending; success or failure is unknown');
 $('[data-outcome]').textContent=ending+(outcome?w(' · 实际累计回报 ',' · Actual total return ')+outcome.return_sum.toFixed(2):'');
 $('[data-outcome]').dataset.result=outcome?.success===true?'success':outcome?.complete?'complete':'partial';
 $('[data-ending]').textContent=outcome?.complete?w('直接看结局','Jump to ending'):w('看片段末尾','Jump to segment end');$('[data-next-task]').textContent=w('下一个任务 →','Next task →');
 $('[data-stages]').hidden=!imag;[...$('[data-stages]').children].forEach((el,i)=>{el.classList.toggle('active',i===ph);el.classList.toggle('done',i<ph);el.querySelector('span').textContent=[w('观察当前位置','Observe'),w('想象 8 种未来','Imagine 8 futures'),w('选出最高分','Choose best score'),w('执行一步，再规划','Act once, replan')][i]});
 $('[data-story]').textContent=!imag?w('正在连续回放：每一步都执行模型选出的动作。','Continuous replay: every step executes the model-selected action.'):[w('先观察。此时环境还没有移动。','Observe first. The environment has not moved.'),w('模型正在预测 8 种候选行动的后果。','Predict the consequences of eight candidate action sequences.'),w('紫色框标出预测回报最高的方案。','The purple border marks the highest predicted return.'),w('只执行选中方案的第一步，然后重新规划。','Execute only the first selected action, then replan.')][ph];
 $('[data-board-title]').textContent=w('实际仿真环境','Actual simulator');$('[data-count]').textContent=(idx+1)+' / '+data.decisions.length;$('[data-board-note]').textContent=data.domain==='MPE'?w('实心圆 = 实际位置；虚线 = 当前查看方案的模型预测。','Solid dots = actual positions; dashed paths = the inspected model prediction.'):data.domain==='SMAC'?w('位置与血量的示意回放，不是 StarCraft II 客户端录像。','Schematic replay of recorded positions and health, not StarCraft II client footage.'):w('身体与关节来自物理仿真；多个控制器共享同一身体。','Body and joint positions come from physics; controllers share one body.');
 $('[data-pred-view]').value=predView;$('[data-pred-label]').textContent=w('预测内容','Prediction view');$('[data-pred-view]').options[0].textContent=w('状态变化','State changes');$('[data-pred-view]').options[1].textContent=w('累计回报','Cumulative return');$('[data-future-panel]').hidden=!imag;root.querySelector('.explorer-grid').classList.toggle('rollout-only',!imag);$('[data-future-title]').textContent=w('同一状态出发的 8 个候选','Eight candidates from the same state');$('[data-future-note]').textContent=predView==='reward'?w('曲线是真实模型逐步预测的累计回报。','Curves show cumulative model-predicted returns.'):data.domain==='SMAC'?w('血量比例来自预测观测；条形范围为 0–1，数值保留模型原始输出。','Health ratios come from predicted observations. Bars span 0–1; numbers retain raw predictions.'):data.forward_position_index!==undefined?w('曲线为世界模型预测的前进位置 x；对各智能体的预测取平均，不是关节动画。','Curves show predicted forward x, averaged over agent observations; they are not joint animations.'):data.domain==='MPE'?w('虚线是真实模型预测的受控智能体轨迹。点击可单独查看；红色对手不在预测图中。','Dashed paths are model predictions for controlled agents. Click to inspect; uncontrolled opponents are omitted.'):w('曲线是真实模型逐步预测的累计回报，不是空间轨迹或仿真结果。','Curves show cumulative model-predicted returns, not spatial trajectories or simulator outcomes.');
 world($('[data-board]'),d,frac);
 if(imag)cards.forEach((o,i)=>{o.b.classList.toggle('winner',reveal&&i===d.selected);o.b.classList.toggle('inspected',selected===i);o.b.classList.toggle('dimmed',reveal&&i!==d.selected);o.label.textContent=w('方案 ','Option ')+(i+1);o.badge.textContent=reveal&&i===d.selected?'✓':'';o.score.textContent=reveal?w('得分 ','Score ')+d.scores[i].toFixed(2):w('预测中…','Predicting…');prediction(o.canvas,d,i,ph===0?0:clamp((time-1.4)/3.5,0,1)*data.horizon)});
 $('[data-play]').textContent=playing?w('暂停','Pause'):w('播放','Play');$('[data-replay]').textContent=w('从头播放','Restart');$('[data-next]').textContent=w('下一步 →','Next →');$('[data-slider]').value=idx;$('[data-progress]').style.width=100*time/duration()+'%';
 $('[data-protocol]').textContent=(data.outcome?.complete?w('整局真实记录。','Complete recorded episode. '):w('未完成回合的片段。','Partial episode recording. '))+w('真实模型输出 · '+data.decisions.length+' 次连续决策 · 每次 8 个候选 · 预测未来 '+data.horizon+' 步。使用已有检查点；单局结果不代表平均成绩。','Actual model outputs · '+data.decisions.length+' continuous decisions · 8 candidates · '+data.horizon+' predicted steps. Existing checkpoints; a single example does not establish aggregate performance.');
 $('[data-detail-title]').textContent=w('数据来源与一步预测误差','Provenance and one-step prediction error');let p=d.predicted_obs[d.selected][1],sum=0,n=0;p.forEach((row,a)=>row.forEach((v,k)=>{sum+=(v-d.next_obs[a][k])**2;n++}));$('[data-detail]').textContent=w('选中方案的一步观测 RMSE：','Selected candidate one-step observation RMSE: ')+Math.sqrt(sum/n).toFixed(4)+w('。此值直接比较原始观测向量，不同任务量纲不同。动画只在记录的真实状态间插值，预测从未当作真实执行结果。下载文件含模型哈希、动作、完整预测观测和奖励。','. Computed on raw observations; scales differ by task. Playback interpolates recorded states, and predictions are never substituted for execution. The download includes checkpoint hashes, actions, full predicted observations and rewards.');
 }
 async function load(id){const ticket=++version;task=id;data=null;playing=false;$('[data-player]').hidden=true;$('[data-status]').hidden=false;$('[data-status]').textContent=tr('正在载入真实轨迹…','Loading recorded trajectories…');all('[data-task]').forEach(b=>{b.classList.toggle('active',b.dataset.task===id);b.setAttribute('aria-pressed',String(b.dataset.task===id))});try{let d=cache[id]||await fetch('assets/imagination/'+id+'.json?v=episodes-20260927').then(r=>{if(!r.ok)throw Error(r.status);return r.json()});if(ticket!==version)return;if(d.domain==='MPE'){const pts=d.decisions.flatMap(x=>[x.state,x.next_state]).flatMap(s=>[...s.agents,...s.landmarks.filter(l=>!l.boundary)]);d.displayExtent=Math.max(1.3,...pts.map(p=>Math.max(Math.abs(p.x),Math.abs(p.y))))*1.12}else if(d.domain==='SMAC'){const pts=d.decisions.flatMap(x=>[...x.state.agents,...x.state.enemies,...x.next_state.agents,...x.next_state.enemies]);const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y);d.displayBounds={xs,ys,cx:(Math.min(...xs)+Math.max(...xs))/2,cy:(Math.min(...ys)+Math.max(...ys))/2}}cache[id]=d;data=d;idx=0;time=0;last=0;selected=null;playing=true;$('[data-slider]').max=d.decisions.length-1;$('[data-download]').href='assets/imagination/'+id+'.json';$('[data-player]').hidden=false;$('[data-status]').hidden=true;render()}catch(e){if(ticket!==version)return;$('[data-status]').textContent=tr('加载失败，请重新点击任务重试。','Could not load this task. Click its button to retry.');console.error(e)}}
 try{available=await fetch('assets/imagination/manifest.json?v=episodes-20260927').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(m=>{taskInfo=Object.fromEntries(m.tasks.map(t=>[t.task,t]));return m.tasks.filter(t=>t.available).map(t=>t.task)})}catch(e){$('[data-status]').textContent=tr('任务清单加载失败，请刷新重试。','Could not load task list. Please refresh.');console.error(e);return}
 for(const [id,label]of tasks){const b=document.createElement('button');b.dataset.task=id;b.textContent=label;b.disabled=!available.includes(id);b.addEventListener('click',()=>load(id));$('[data-tasks]').appendChild(b)}
 for(let i=0;i<8;i++){let b=document.createElement('button');b.className='future-card';b.innerHTML='<div class="future-head"><span></span><b></b></div><canvas width="240" height="180"></canvas><div class="future-score"></div>';b.setAttribute('aria-label','Inspect candidate '+(i+1));$('[data-cards]').appendChild(b);cards.push({b,label:b.querySelector('span'),badge:b.querySelector('b'),canvas:b.querySelector('canvas'),score:b.querySelector('.future-score')});b.addEventListener('click',()=>{selected=i;playing=false;time=5.5;render()})}
 all('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;time=0;last=0;selected=null;render()}));$('[data-lang]').addEventListener('click',()=>{lang=lang==='zh'?'en':'zh';render()});$('[data-pred-view]').addEventListener('change',e=>{predView=e.target.value;render()});$('[data-play]').addEventListener('click',()=>{selected=null;playing=!playing;last=0;render()});$('[data-replay]').addEventListener('click',()=>{idx=0;time=0;last=0;selected=null;playing=true;render()});$('[data-ending]').addEventListener('click',()=>{if(data){mode='rollout';idx=data.decisions.length-1;time=.65;playing=false;selected=null;render()}});$('[data-next-task]').addEventListener('click',()=>{load(available[(available.indexOf(task)+1)%available.length])});$('[data-next]').addEventListener('click',()=>{if(data){idx=Math.min(idx+1,data.decisions.length-1);time=0;selected=null;render()}});$('[data-slider]').addEventListener('input',e=>{idx=Number(e.target.value);time=0;selected=null;render()});
 new IntersectionObserver(es=>{visible=es[0].isIntersecting;last=0},{threshold:.05}).observe(root);
 function tick(now){if(data&&playing&&visible&&!document.hidden&&last){time+=Math.min((now-last)/1000,.1);if(time>=duration()){if(idx===data.decisions.length-1){time=duration();playing=false}else{time=0;idx++}selected=null}render()}last=now;requestAnimationFrame(tick)}requestAnimationFrame(tick);await load('8m');
})();
